
let payloadObj = {
    speed: 0.0,
    distance: 0.0,
    event_flag: 1024,
    fl_level: 0,
    gpsSignal: -92,
    gpsStatus: "A",
    canValid: 0,
    direction: 0,
    extBatVol: 0,
    intBatVol: 0,
    satellites: 0,
    HDOP: 0,
    temperature: 0.0,
    reserved15: 0.0,
    packetEventCode: 1,
    eventCode: 0,
    isLiveEventCode: true,
    rawString: "",
    uniqueId: "",
    serialNo: "",
    date: "",
    time: "",
    timestamp: 0,
    imeiNo: "",
    latitude: 0.0,
    callPhpForOldPack: false,
    longitude: 0.0,
    vehicleRegNumber: "",
    latitudeDir: "",
    longitudeDir: "",
    altitude: 0.0,
    PDOP: 0.0,
    miscellaneous: "",
    frameNumberString: "",
    delta_distance: 0.0,
    analog2: 0.0,
    xval: 0,
    yval: 0,
    zval: 0,
    clientId: "DEFAULT",
  };
  let sensorObj = {
    userId: 0,
    loginTimeStamp: 0,
    logoutTimeStamp: 0,
    loginStatus: 0,
    logoutStatus: 0,
    rfid: "00",
    packetEventCode: 0,
    eventCode: 0,
    isLiveEventCode: false,
    rawString: "",
    uniqueId: "",
    serialNo: "1",
    date: "",
    time: "",
    timestamp: 0,
    latitude: 0.0,
    callPhpForOldPack: false,
    longitude: 0.0,
    altitude: 0.0,
    PDOP: 0.0,
    delta_distance: 0.0,
    analog2: 0.0,
    xval: 0,
    yval: 0,
    zval: 0,
    clientId: "DEFAULT",
  };

  let obdObj = {
    uniqueId: 0,
    timestamp: 1680195161,
    latitude: 0,
    longitude: 0,
    extBatVol: 0,
    intBatVol: 0,
    engineLoad: 0,
    tankLevel: 0,
    throttle: 0,
    coolant: 0,
    intakeAirTemp: 0,
    engineOilTemp: 0,
    imap: 0,
    vehicleSpeed: 0,
    warmups: 0,
    rpm: 0,
    obdDistance: 0.0,
    maf: 0,
    fuelRail: 0,
    runTime: 0,
    mil: 0,
    obdStandards: 0,
    tellTale: 0,
    pto_drive_engagement: 0,
    engine_torque_percent: 0,
    service_distance: 0,
    gross_combination_vehicle_weight: 0,
    selected_gear: 0,
    current_gear: 0,
    fuel_consumption: 0,
    fuel_level: 0,
    fuel_rate: 0,
    fuel_economy: 0,
    accelerator_pedal_pos: 0,
    vehicle_weight: 0,
    air_suspension_pressure_front_axle_left: 0,
    air_suspension_pressure_front_axle_right: 0,
    air_suspension_pressure_rear_axle_left: 0,
    air_suspension_pressure_rear_axle_right: 0,
    state_of_charge: 0,
    battery_pack_voltage: 0,
    battery_total_current: 0,
    battery_total_power: 0,
    odo_distance: 0,
    lamp_status: 0,
    hydraulic_oil_filter: 0,
    air_filter: 0,
    no_charging: 0,
    low_fuel: 0,
    engine_temp_high: 0,
    hydraulic_oil_temp_high: 0,
    water_in_fuel: 0,
    low_oil_pressure: 0,
    roller_speed: 0,
    plusCode: 0,
    vibration_on: 0,
    axle_position: 0,
    tire_position: 0,
    tire_pressure: 0,
    tire_temperature: 0,
    tire_air_leakage_rate: 0,
    tire_sensor_enable_status: 0,
    tire_status: 0,
    tire_sensor_electric_fault: 0,
    extended_tire_pressure_support: 0,
    tire_pressure_threshold_detection: 0,
    extended_tire_pressure: 0,
    cpc_system_type: 0,
    required_tire_pressure: 0,
    cpc_tire_id: 0,
    cpc_graphical_position: 0,
    cpc_tire_location: 0,
    cpc_ttm_id: 0,
    secondary_air_status: 0,
    catalyst_temperature_bank1_sensor1: 0,
    catalyst_temperature_bank1_sensor2: 0,
    barometric_pressure: 0,
    distance_since_mil: 0,
    commanded_egr: 0,
    egr_error: 0,
    drive_cycle_status: 0,
    ambient_air_temperature: 0,
    fuel_system_status: 0,
    short_term_fuel_trim_bank_1: 0,
    long_term_fuel_trim_bank_1: 0,
    timing_advance: 0,
    oxygen_sensors_present: 0,
    oxygen_sensor_1_voltage: 0,
    oxygen_sensor_2_voltage: 0,
    commanded_evaporative_purge: 0,
    control_module_voltage: 0,
    absolute_load_value: 0,
    relative_throttle_position: 0,
    oxygen_sensor_1_short_term_fuel_trim: 0,
    oxygen_sensor_2_short_term_fuel_trim: 0,
    can_raw_data: "",
    fuel_used: 0.0,
  };

  const DEFAULT_EVENT_FLAG = "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0";

  
module.exports = {
    payloadObj,
    sensorObj,
    obdObj,
    DEFAULT_EVENT_FLAG
}